# DEFINES ALL SERVICES TO BE RUN IN DOCKER CONTAINERS
services:
  mariadb:
    container_name: mariadb
    build: 
        context: ./requirements/mariadb
        dockerfile: Dockerfile
    init: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - docker-network
    image: mariadb

  nginx:
    container_name: nginx
    build: 
        context: ./requirements/nginx
        dockerfile: Dockerfile
    init: true
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    ports:
      - "443:443" #https PORT
    volumes:
      - wordpress:/var/www/html 
    networks:
      - docker-network
    depends_on:
      - wordpress
    image: nginx

  wordpress:
    container_name: wordpress
    build: 
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    init: true
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
      - WORDPRESS_DIR=${WORDPRESS_DIR}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - wordpress:/var/www/html
      # Creats a "portal" between wordpress container and the VM's harddrive (defined in volumes section)
    networks:
      - docker-network
    depends_on:
      - mariadb
      - redis
    image: wordpress

  redis:
    build: 
        context: ./requirements/bonus/redis
        dockerfile: Dockerfile
    container_name: redis
    restart: always
    networks:
      - docker-network
    image: redis

  ftp: # FTP SERVER TO UPLOAD FILES TO WORDPRESS
    build:
        context: ./requirements/bonus/ftp
        dockerfile: Dockerfile
    container_name: ftp
    restart: always
    env_file:
      - .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - WORDPRESS_DIR=${WORDPRESS_DIR}
    volumes:
      - wordpress:/var/www/html
    ports:
      - "21:21" # COMMAND PORT
      - "21000-21010:21000-21010" # DATA PORTS RANGE FOR PASSIVE MODE
    networks:
      - docker-network
    depends_on:
      - wordpress
    image: ftp

  adminer: # DATABASE MANAGEMENT INTERFACE
    build:
        context: ./requirements/bonus/adminer
        dockerfile: Dockerfile
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080" # ACCESS ADMINER VIA http://demrodri.42.fr:8080
    networks:
      - docker-network
    image: adminer

  static-site:
    container_name: static-site
    build:
        context: ./requirements/bonus/static-site
        dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80" # http PORT
    image: static-site

  portainer: # DOCKER MANAGEMENT INTERFACE
    build:
        context: ./requirements/bonus/portainer
        dockerfile: Dockerfile
    container_name: portainer
    ports:
      - "8000:8000" # EDGE AGENT PORT - to manage remote Docker environments
      - "9443:9443" # HTTPS PORT FOR PORTAINER UI
      - "9000:9000" # HTTP PORT FOR PORTAINER UI
    networks:
      - docker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Allows Portainer container to communicate
      - portainer:/data                           # with the Docker daemon on the host machine
    image: portainer                              # so it can manage Docker containers
    restart: always


# CONNECTS "DOCKER WORLD" WITH "VM's HARDDRIVE's WORLD"
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/demrodri/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/demrodri/data/wordpress

  portainer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/demrodri/data/portainer


# DEFINES CUSTOM NETWORK TO CONNECT ALL SERVICES
networks:
  docker-network:
    name: docker-network
    driver: bridge # prvides network isolation between host and containers
                   # allows to resolve service names to IP addresses within the network